# Generated by Django 3.1.3 on 2020-11-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='button',
            field=models.CharField(default='upload', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='description',
            field=models.TextField(default='button'),
            preserve_default=False,
        ),
    ]
