# Generated by Django 3.1.3 on 2020-11-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20201125_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Electronics', 'Electronics'), ('Fruits', 'Fruits'), ('Detergents', 'Detergents'), ('Spices', 'Spices'), ('Eggs', 'Eggs'), ('Cosmetic', 'Cosmetic')], max_length=15),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Electronics', 'Electronics'), ('Fruits', 'Fruits'), ('Detergents', 'Detergents'), ('Spices', 'Spices'), ('Eggs', 'Eggs'), ('Cosmetic', 'Cosmetic')], default='Food', max_length=15),
        ),
    ]
