# Generated by Django 3.1.3 on 2020-11-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201125_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Electronics', 'Electronics'), ('Fruits', 'Fruits'), ('Detergents', 'Detergents'), ('Spices', 'Spices'), ('Eggs', 'Eggs'), ('Perfumes', 'Perfumes'), ('Neckless', 'Neckless'), ('Beads', 'Beads'), ('Earings', 'Earings')], max_length=15),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Electronics', 'Electronics'), ('Fruits', 'Fruits'), ('Detergents', 'Detergents'), ('Spices', 'Spices'), ('Eggs', 'Eggs'), ('Perfumes', 'Perfumes'), ('Neckless', 'Neckless'), ('Beads', 'Beads'), ('Earings', 'Earings')], default='Food', max_length=15),
        ),
    ]
