# Generated by Django 3.1.3 on 2020-11-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201125_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='button',
        ),
    ]
